### ISSUE TITLE
Adding an endpoint and authentication

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt-contrib-xapi#14]
When we create a course there should be an option to add an endpoint and authentication information using which the course will pass the xAPI information to the LRS providing the end point.

**Comment by ryanrolds** [comment]
There may be a better way, but I've been adding `?agent={"mbox":"mailto:name@domain.com"}&endpoint=https://domain.com/data/xAPI&auth=Basic xxxxxxxxxx` to the query string.

**Comment by brian-learningpool** [comment]
This is implemented now in the `develop` branch.
