### ISSUE TITLE
Window unload occurring before terminated/suspended events are fired

### ISSUE THREAD

**Issue by barrymckay397** [adaptlearning/adapt-contrib-xapi#20]
This is intermittent, sometimes one of the statements is fired off successfully, sometimes both, sometimes none

**Comment by brian-learningpool** [comment]
Sending AJAX requests on a window close is unreliable at the best of the times.  As we're now in 2019 it's probably worth investigating the `navigator.sendBeacon()` method (https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) to accomplish this.

**Comment by moloko** [comment]
no support for `sendBeacon` in either IE or Safari for iOS though, that’s a pretty big gap in coverage.

One workaround could be to update this plugin to add a close button into the course navigation bar and require that the learner uses that to close to course. 

you could also have it display a browser prompt via `beforeunload` to warn learners who try to close the the course via the browser close button that doing so may cause loss of tracking data

**Comment by moloko** [comment]
or, instead of showing a prompt via `beforeunload` in all browsers you use `sendBeacon` for those that support it and reserve the prompt for those that don’t. i think that would then cover all browsers apart from Safari for iOS (which at least may add support for `sendBeacon` in future - whereas IE definitely will not)

**Comment by danielstorey** [comment]
@moloko that sounds like a sensible approach

**Comment by brian-learningpool** [comment]
Safari for iOS supports `navigator.sendBeacon()` as of version 11.1.

**Comment by moloko** [comment]
there's also a couple of polyfills for `sendBeacon` that could be worth investigating?

https://github.com/miguelmota/Navigator.sendBeacon
https://github.com/kronicker/sendbeacon-polyfill (fork of the above)

**Comment by danielstorey** [comment]
I don't think we can use `sendBeacon` as you can't set custom headers, making authentication impossible in most cases.

According to w3c:

> The sendBeacon() method does not provide ability to customize the request method, provide custom request headers, or change other processing properties of the request and response. Applications that require non-default settings for such requests should use the [FETCH] API with keep-alive flag set to true.

https://w3c.github.io/beacon

**Comment by brian-learningpool** [comment]
Thanks @danielstorey, that is definitely going to be an issue.

**Comment by brian-learningpool** [comment]
Resolved in https://github.com/adaptlearning/adapt-contrib-xapi/pull/59.
