### ISSUE TITLE
#Unable to setup listeners for xAPI

### ISSUE THREAD

**Issue by shonesque** [adaptlearning/adapt-contrib-xapi#31]
I have manually downloaded the extension and added to my Framework based project. The config.json file has been updated as per documentation instructions. 

The framework version I am using is the 3.2.1.

The extensions is correctly added under the src/extensions location.

During the build, the *Error: Cannot find module 'src\extensions\adapt-contrib-xapi\scripts\post-build.js'* is prompted. After the build, I encounter the *Unable to setup listeners for xAPI* error in the browser console. 

Please advise.

**Comment by moloko** [comment]
hmm that's odd, thought that had been fixed by https://github.com/adaptlearning/adapt_framework/issues/2212

**Comment by brian-learningpool** [comment]
@shonesque, you actually have two issues here.

v3.2.1 of the framework should resolve the  "Cannot find module" warning.  All this step does is swap in the Activity ID and the code defaults to the current URL if it isn't set.

The "Unable to setup listeners for xAPI" indicates a problem with the xAPI wrapper failing to initialise.  How are you launching the course?  This warning will show by default if you preview the course in the authoring tool.  You would need to augment the URL to pass in the actor, endpoint, etc.

**Comment by shonesque** [comment]
Hi Brian.
Hi Matt.

Thank you for the fast turnaround.

I have generated a launch url based on the Tin Can launch protocol.

All of the details that are needed (location, lrs endpoint, key:secret pair and the UID) were added manually.

The Cannot find module warning error (the one prompted in the console during the build process) has been indeed been adressed with correctly ading the URI for the course.

The course is generated using the framework, and my initial tests indicates that the xApi statements for passing/failing the assessment are working by using the adapt-contrib-xApi extension.

I am not entirely sure if there should be several other http requests to PUT the rest of the details (user progress, block/article/Content object completion), should also be reported.

Is there any aspect I should be aware of, regarding the extension itself?

Since the thread issue is addressed, I think it is safe for us to close it.

Thank you,
Cosmin

**Comment by brian-learningpool** [comment]
Hi Cosmin, 

The extension can be configured to handle course, contentobject, article, block and component completion.  Have a look at the [example.json](https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/example.json#L13-L32)for a sample configuration on how to toggle the listeners on these objects.  There is also some information in the [README](https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/README.md) which should guide you through the default options.  Let me know if you notice anything missing.

Hope this helps.
