### ISSUE TITLE
Getting a Fatal Error: ENOENT: no such file

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt-contrib-xapi#40]
Hi I am running the newest Framework 2.2.7 and Authoring Tool 0.6.0. I have built a small course and enabled the xAPI extension in the authoring tool. For some reason though when I try to preview the course I am getting this error...

Running "javascript:compile" (javascript) task
Fatal error: Error: ENOENT: no such file or directory, open 'C:\Users\MikeS-PC\adapt_authoring\temp\5b4903a233e2918417c6d9be\adapt_framework\src\core\js\enums\completionStateEnum.js'
In module tree:
    core/js/app
      extensions/adapt-contrib-xapi/js/adapt-contrib-xapi

**Comment by moloko** [comment]
hi @mike-st unfortunately the xapi plugin is not compatible with Framework v2.x - it does mention this in the README:
> xAPI is an extension intended for use with the Adapt framework version 3.0 or greater

but it should also have a "framework" entry in bower.json to warn you if you try to install it in an unsupported version of the framework - I see this is missing so I'll get it added.

**Comment by mike-st** [comment]
Thanks @moloko. Makes sense, but got confused by the readme as it states it works with Authoring Tool too but right now the Authoring tool is only running 2.2.7. Thanks for the clarification.

**Comment by moloko** [comment]
@mike-st for various reasons, the authoring tool defaults to v2.x of the framework but you can update it to v3.x - providing you understand the implications of doing so!
