### ISSUE TITLE
Can't seem to get the Assessment score to populate

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt-contrib-xapi#42]
Hi not sure why but everything else is working for me using the xAPI extension except the assessment scoring data won't populate. Perhaps I am missing a small detail not sure. Here is how I have filled out the config.json...

"_xapi": {
    "_isEnabled": true,
    "_specification": "xAPI",
    "_activityID": "https://mycourse.com/myid",
    "_endpoint": "https://myendpoint.com",
    "_user": "",
    "_password": "",
    "_lang": "en-US",
    "_generateIds": false,
    "_shouldTrackState": true,
    "_coreEvents": {
      "Adapt": {
        "router:menu": true,
        "router:page": true,
        "questionView:recordInteraction": true,
        "assessments:complete": true
      },
      "contentobjects": {
        "change:_isComplete": true
      },
      "articles": {
        "change:_isComplete": true
      },
      "blocks": {
        "change:_isComplete": true
      },
      "components": {
        "change:_isComplete": true
      }
    },
    "_lrsFailureBehaviour": "show"
  },

![scoring-not-coming-up](https://user-images.githubusercontent.com/10455453/48225952-64af8e00-e36c-11e8-9da1-d263923e4eb2.jpg)

**Comment by brian-learningpool** [comment]
Hi @mike-st, from your screenshot it looks like you're using Scorm Cloud.  I'm not sure what statement exactly Scorm Cloud interrogates to surface the score, but currently the xAPI extension sends a separate statement for Assessment completion.  You can find the code here:
https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/js/adapt-contrib-xapi.js#L704-L738

Can you verify that you see an Assessment statement at least?

**Comment by mike-st** [comment]
Hi and thanks @brian-learningpool for your help. I apologize as I am very new to xAPI and may have mixed something up. You are correct I am using Scorm Cloud and it is doing a good job of tracking everything. I have set up the "**_activeID**" to go to my courses url (ex.) "https://cloud.scorm.com/sandbox/content/courses/coursearea/xAPITestCourse-5x5x5x5x5x". I have also set up the "**_endpoint**" to go to (ex.) "https://cloud.scorm.com/tc/coursearea/sandbox/".  

I am wondering if I should extend the statement time delay as it is at 500, maybe that is not enough time for Scorm Cloud? Also I checked in the browsers console log and everything there is feeding through fine. Sorry but still stumped if you can help? Thanks in advance...

![assessment](https://user-images.githubusercontent.com/10455453/48270099-3632c100-e407-11e8-813f-76b19a01259a.jpg)

**Comment by brian-learningpool** [comment]
Hi @mike-st, apologies for the delay in getting back to you.

Your configuration looks fine.  My point is that there is a specific "assessment passed" statement sent via the xAPI extension.  This most likely is not what Scorm Cloud is using to track and store agains the course score which it surfaces on the dashboard page.

**Comment by brian-learningpool** [comment]
Hi @mike-st, I know our last communication was a year ago but I've been doing some testing recently on Scorm Cloud and it appears that when the pass/fail statements are grouped correctly, the assessment score, etc. does display.  This is dependent on assessment being grouped as part of the course, so the statement has `contextActivities.grouping[]` set. 
<img width="878" alt="Screenshot 2019-11-22 at 12 33 00" src="https://user-images.githubusercontent.com/1327471/69426137-66a08100-0d24-11ea-9413-f163f3733b5b.png">

The good news is that I'm working on a PR right now to address this as part of #50, and it should be ready shortly as part of the 0.8 release.

**Comment by brian-learningpool** [comment]
Resolved in v0.8.
