### ISSUE TITLE
Stuck on loading screen if LRS connection fails

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt-contrib-xapi#43]

**Comment by danielstorey** [comment]
If there is an error connecting to the LRS or `!_shouldTrackState` the course will stick on the loading screen. This is due to offline storage currently only releasing Adapt.wait on `xapi:stateLoaded`

In addition any LRS error messages which are displayed via `notify` will be dismissed almost immediately when the page loads. Any such messages should remain on screen until the user dismisses them.

**Comment by brian-learningpool** [comment]
Fixed in v0.5.1.
