### ISSUE TITLE
Activity type for interactions should be http://adlnet.gov/expapi/activities/cmi.interaction

### ISSUE THREAD

**Issue by garemoko** [adaptlearning/adapt-contrib-xapi#63]
The xAPI spec states
> Interaction Activities SHOULD have the Activity type http://adlnet.gov/expapi/activities/cmi.interaction

This means that questions, because they use the special Interaction Activity properties, should use this activity type. Instead they use http://adlnet.gov/expapi/activities/question. 

See:
https://github.com/adaptlearning/adapt-contrib-xapi/blob/7f148b69e6d774130a02513046beeb4249ac60d7/js/adapt-contrib-xapi.js#L522

But actually this is the code that get's used: 
https://github.com/adaptlearning/adapt-contrib-xapi/blob/7f148b69e6d774130a02513046beeb4249ac60d7/js/adapt-contrib-xapi.js#L572

Looks like this might also be an issue with the ADL Wrapper since cmi.interaction is not listed https://github.com/adlnet/xAPIWrapper/blob/master/src/activitytypes.js#L7

**Comment by brian-learningpool** [comment]
Hi @garemoko, thanks for raising.  It looks like this was changed in https://github.com/adaptlearning/adapt-contrib-xapi/commit/0e690ece99bf7d4cbe278a48d0dbabd3131ca8ea.

**Comment by brian-learningpool** [comment]
PR for this issue is now up at https://github.com/adlnet/xAPIWrapper/pull/154.

**Comment by oliverfoster** [comment]
closed stale
