### ISSUE TITLE
Question instruction is used as the objects description for question interaction statements

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-xapi#68]
For question statements the object definition description uses the question instruction text value [here](https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/js/adapt-contrib-xapi.js#L587). 

For most use cases the question text and description is likely to be in the body element.

Would it be more useful to use the body element?

**Comment by kevindoherty30** [comment]
Having looked at a few statements from questions types, I would agree that using the body element would be a lot more useful, and provide a lot more flexibility when viewing the data on an LRS.

In our course setup we don't always use the instruction and where we have it is pretty meaningless information as it is used for instruction only.

I don't know if anyone else has ever used the instruction text to provide anything of additional value that I'm not considering but i would be all for dropping the instruction and taking the body element of questions.

**Comment by dancgray** [comment]
Thanks @kevindoherty30, agreed. The body text will likely be HTML, do you think this should be encoded or escaped before sending as a statement?

**Comment by brian-learningpool** [comment]
Hi @dancgray, apologies for the late reply.  I think this should definitely be escaped.

**Comment by brian-learningpool** [comment]
Closing as this is in place for v0.8. Thanks for testing @dancgray.
