### ISSUE TITLE
Is there a way to show the learnerInfo within course body text?

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt-contrib-xapi#72]
Spoor extended the course _globals so that {{_globals._learnerInfo.firstname}} could be used within body text.

**Comment by moloko** [comment]
relevant bit of code in spoor is here: https://github.com/adaptlearning/adapt-contrib-spoor/blob/b2af716f4de77a46ff19be4aa595058b3080b3bb/js/adapt-stateful-session.js#L43-L53

**Comment by RobertPeek** [comment]
Has this functionality not been included in the xAPI plugin then? Or does it work/store the data differently?

**Comment by moloko** [comment]
@RobertPeek from what I can see it's got a function there to retrieve the data from the LRS - so you can access the learner's details using JavaScript - but an extra step is required to allow you to be able to do the same from the course JSON

**Comment by brian-learningpool** [comment]
This is handled as part of the PR https://github.com/adaptlearning/adapt-contrib-xapi/pull/76.

**Comment by brian-learningpool** [comment]
@RobertPeek this is now in v0.8.
