### ISSUE TITLE
Assessment ID should probably be passed as an extension on the xAPI statement object

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-xapi#77]
In the [Assessment](http://github.com/adaptlearning/adapt-contrib-assessment) extension, it's possible to give a user-friendly ID in lieu of the article `_id` value.  The problem is that this is not passed in the xAPI `passed` or `failed` statement.  As such, it's currently very difficult to parse such xAPI statements to extract the statement for a specific assessment. 

Ideally the Assessment ID would be passed as an `extension` on the xAPI statement.  In addition we could probably also add Attempt ID as defined in the [TinCan registry]( https://registry.tincanapi.com/#home/extensions).

**Comment by oliverfoster** [comment]
closed as stale
