### ISSUE TITLE
xAPIWrapper sendState sending state value as [object Object]

### ISSUE THREAD

**Issue by jamieking1996** [adaptlearning/adapt-contrib-xapi#87]
Angular - 9.1.0
xAPI Wrapper - 1.11.0

Hi there. I'm currently working on a test Angular project, which configures the xAPIWrapper with Learning Locker LRS details, and then combining an Adapt Learning Pool course with the xAPI extension enabled (currently just through an iframe). The xAPI extension is configured as default, as I don't need to configure the LRS details in there, as this is in my Angular application.

So far I have got everything to work well together in sending statements etc, however when the Adapt course attempts to send state for a component stateId, the state it sends seems to be the string "[object Object]", which results in the content of the state being set as null in learning locker. 

Once I reload the page, the adapt course fails from the getState attempt, as it returns the string "[object Object]". In the adapt.min.js, this fails on line 12036 (in the getState function) as it cannot JSON.parse the response.

I am aware of the fact that I am creating my own LRS configuration which you may not have intended an adapt course to be used with, but I assume you have as you provide offline xAPI javascript examples. If your adapt courses are intended for this kind of configuration, I'm not quite sure if this is an issue from your end, or ADL's xAPIWrapper, or if it's with my configuration.

If there are any potential faults with my own configuration that you could think of, please let me know.

Thanks!

**Comment by oliverfoster** [comment]
closed as stale
