### ISSUE TITLE
Language selection is not retained on re-opening in multi language courses

### ISSUE THREAD

**Issue by deltanetdan** [adaptlearning/adapt-contrib-xapi#88]
### Subject of the issue
In a multi language course the user has to choose their language each time they return to a course.

### Your environment
* version FW v4.5.0, adapt-contrib-xapi v0.8.3

### Steps to reproduce
Create a course with language picker , xAPI and bookmarking plugin. Include at least two languages.
Start the course after uploading to your LRS (SCORM Cloud in this case)
Select a language and get part way through the course.
Close and re-open the course.

Note: 
xapi _shouldTrackState = true
language picker _showOnCourseLoad = true

### Expected behaviour
On re-opening, the course should be in the language selected on the previous launch. The user should be able to return to the bookmarked location.

### Actual behaviour
The user is always asked to select a language. If they select the same language as the previous attempt they will be returned to the bookmark position.

If language picker _showOnCourseLoad is set to false the user is always returned to the default language and any bookmark progress in a non default language is lost.

**Comment by deltanetdan** [comment]
@kevindoherty30 did you find a solution for this?

**Comment by deltanetdan** [comment]
I can confirm that this is an issue in framework v5.11.0 using the latest xAPI and language picker plugins.

**Comment by cahirodoherty-learningpool** [comment]
Further investigation on this has show that the issue lies with the offline storage. Since the code was converted to an ES6 class it is instantiating, when it shouldn't. This results in the ready state being called earlier than it should, so the language property set by xAPI is not present when the offline storage is consumed by languagePicker.

Further API work will depend on [core issue #20](https://github.com/adaptlearning/adapt-contrib-core/issues/20) and may not be needed depending on the solution in Core

**Comment by oliverfoster** [comment]
@cahirodoherty-learningpool I can't replicate this, the ready state is triggered [here](https://github.com/adaptlearning/adapt-contrib-core/blob/f4a589902c565d5749053ea3d091bda5f8aa4ed5/js/offlineStorage.js#L89) from [here](https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/js/XAPIIndex.js#L40) after [this](https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/js/XAPIIndex.js#L35) triggered from [here](https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/js/XAPI.js#L151). 

Spoor does something almost identical and that seems to work well. Could you have another look?

**Comment by oliverfoster** [comment]
Stale
